using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.Medieval.Trading;

[GenerateTypedNameReferences]
public sealed partial class TradingBidReceiptWindow : DefaultWindow
{
    public event Action<int>? OnConfirm;

    public TradingBidReceiptWindow(int maximumAmount)
    {
        RobustXamlLoader.Load(this);
        AmountSlider.MinValue = 1;
        SetMaximumAmount(maximumAmount);
        ConfirmButton.OnPressed += _ =>
        {
            OnConfirm?.Invoke(AmountSlider.Value);
            Close();
        };
    }

    public void SetMaximumAmount(int maximumAmount)
    {
        AmountSlider.MaxValue = maximumAmount;
        AmountSlider.Value = maximumAmount;
    }
}
